Repository jghjianghan/South-Korea-Covid19-IS, pull requests merged in 2021-01, with the labels that each got.

#47 Closes Revisi Fitur admin
  Database/query export/covid19.sql
  controller/adminController.php
  router.php
  view/addAccount.php
  view/addData.php
  view/changePassword.php
  view/dataRegionalAdmin.php
  view/js/adminScript.js
  view/login.php
Labels: back-end, bug, database, front-end

#58 Fix Admin Integration Revision
  controller/adminController.php
  model/AdminTable.php
  router.php
  view/addAccount.php
  view/addData.php
  view/changePassword.php
  view/js/adminScript.js
  view/login.php
Labels: bug

#61 Allow Adding Data in the past
  Database/query export/covid19.sql
  controller/adminController.php
  router.php
  view/addData.php
Labels: back-end, enhancement, front-end

#66 Reset tanggal
  view/dataOverall.php
  view/dataRegional.php
  view/js/dataOverallManager.js
  view/js/dataRegionalManager.js
Labels: enhancement, front-end
